Epic/registration
wam82/teamname-soen341project2023 pull request #103
Opened 2023-03-27 18:12 UTC by arcvelit

Merging Salma's code of registration page with main

2023-03-27 18:19 UTC, Razvan-Alexandru requested changes
Make sure your branch is up to date with main. All these changes should not happen

2023-03-27 18:19 UTC, Razvan-Alexandru commented on app/src/App.tsx
> -      <Switch>
This should not be modified

2023-03-27 18:19 UTC, Razvan-Alexandru commented on app/src/LoginPage/LoginPage.js
> -import React, { useState } from 'react';
Why is this page deleted and re-created with a different extension? Also what modification happened here?

2023-03-27 18:19 UTC, Razvan-Alexandru commented on app/src/components/Header/Header.jsx
> -            <svg class="logo-image" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.
What are all these modifications?

2023-04-05 12:56 UTC, wam82 commented on app/src/components/Header/Header.jsx
> -            <svg class="logo-image" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.
This appears to be a modification in the image in the header, it shouldn't break the code. @SalmaAl22 Can you confirm?

2023-04-10 17:27 UTC, SalmaAl22 commented
guys you told me it's been taken care of, the linking to database issue, but why isn't merged to main yet?

2023-04-10 17:28 UTC, wam82 commented
Because there are a couple changes that were made. I'll close to pull request. Assume it to be completed

2023-04-10 17:28 UTC, closed without merging

2023-04-10 17:30 UTC, SalmaAl22 commented
There's is still no registration file in the main!