Epic/managing student profile
wam82/teamname-soen341project2023 pull request #104
Opened 2023-03-27 18:13 UTC by arcvelit

Merging Kevin's code with main

2023-03-27 18:22 UTC, Razvan-Alexandru requested changes
Make sure your branch is up to date with main before merging. There are a lot of changes that should not be here

2023-03-27 23:29 UTC, Amir8Abdullah commented on app/src/components/Header/Header.jsx
> -            <svg class="logo-image" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.
All changes from class to className are nothing. In HTML you use class and in Javascript you use className. They are the exact same thing, but this change needs to be done to make it functional.

2023-04-01 23:55 UTC, KD54321 commented on app/src/App.tsx
> +import Posts from "../src/components/posts/Posts"
resolved

2023-04-17 19:09 UTC, wam82 commented
This pull request is outdated and should no longer be opened

2023-04-17 19:09 UTC, closed without merging