AddedManagingStudentProfile
wam82/teamname-soen341project2023 pull request #54
Opened 2023-02-28 22:05 UTC by KD54321

Added css and react function for managing student profile
Added bootstrap script in index file.

2023-03-01 03:16 UTC, Amir8Abdullah reviewed
We want to use React for this project. Change HTML to react.

2023-03-01 03:21 UTC, Amir8Abdullah requested changes
Needs changes.

2023-03-01 03:21 UTC, Amir8Abdullah commented on app/public/index.html
> -    <title>React App</title>
Revert this change.

2023-03-01 03:21 UTC, Amir8Abdullah commented on app/public/index.html
> +    <link
From line 27-31, what does this do?

2023-03-01 03:21 UTC, Amir8Abdullah commented on app/src/App.tsx
> +      <Manage_Profile/>
You cannot have two pages in a same page. Remove this line.

2023-03-01 03:36 UTC, KD54321 commented on app/public/index.html
> +    <link
its a bootstrap script that links to a css library

2023-03-01 03:40 UTC, KD54321 commented on app/src/App.tsx
> +      <Manage_Profile/>
How are we going to implement this page then?

2023-03-25 18:25 UTC, Amir8Abdullah commented on app/public/index.html
> +    <link
Oh ok.

2023-03-26 01:32 UTC, merged