Bunch of modifications regarding LoginPage, Header and creation of loginHeader
wam82/teamname-soen341project2023 pull request #83
Opened 2023-03-25 18:21 UTC by Amir8Abdullah

1. In .github/workflows/main.yml: change the branch condition from -master to -main.
2. The login page is now fully functional: desgined the full backend handling of the login page.
3. Header: Removed uncesserary part in the header.
4. Login Header: Created a new header for users who are logged in. The correspondant CSS file has been modified as well.

2023-03-25 23:47 UTC, Razvan-Alexandru commented
don't use the same pull request for different tasks plz

2023-03-25 23:47 UTC, Razvan-Alexandru requested changes
Do not use the same pull request for different tasks

2023-03-25 23:55 UTC, Amir8Abdullah commented
It has been added to epic/loginPage.

2023-03-26 00:08 UTC, Razvan-Alexandru commented on .github/workflows/main.yml
> -      - master
do not change here

2023-03-26 00:13 UTC, Razvan-Alexandru submitted a review, later dismissed

2023-03-26 00:14 UTC, Razvan-Alexandru requested changes
do not change main.yml in this branch

2023-03-26 00:16 UTC, Razvan-Alexandru approved these changes

2023-03-26 00:17 UTC, merged